name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Markdown
      uses: actionshub/markdownlint@2.0.2
    - name: Run Shellcheck
      uses: azohra/shell-linter@latest
      with:
        path: "pwnagotchi-launcher-pre, pwnagotchi-viewer"
